export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const SWITCH_CURRENT_PROJECT = 'SWITCH_CURRENT_PROJECT';
export const ADD_NEW_ISSUE = 'ADD_NEW_ISSUE';
export const DELETE_ISSUE = 'DELETE_ISSUE';
export const CHANGE_ISSUE_STATUS = 'CHANGE_ISSUE_STATUS';
export const CHANGE_ISSUE_PRIORITY = 'CHANGE_ISSUE_PRIORITY';